### ISSUE TITLE
52破解签到是不是不能用了啊？

### ISSUE THREAD

**Issue by rklhxyk1128** [NobyDa/Script#352]
nodejs 版的，提示脚本待更新

**Comment by NobyDa** [comment]
吾爱加验证了，目前无解；等一阵子看看吧。

**Comment by dukecd33369** [comment]
nodejs 使用post方式 可以正常使用
但是圈x不行 第一次的时候返回的data 提示开启javascript  但是任务实际已经完成了

**Comment by dukecd33369** [comment]
还有 吾爱的cookie 字段最近改过了

**Comment by htcyy** [comment]
surge提示服务器暂停签到，，是不是网站原因




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NobyDa/Script"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月19日(星期五) 凌晨0:45
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [NobyDa/Script] 52破解签到是不是不能用了啊？ (Issue #352)





 
还有 吾爱的cookie 字段最近改过了
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
